// ============================================================
// ARK DECOR — PRODUCT DATABASE
// ============================================================

const PRODUCTS = [
  {
    id: 1,
    name: "Royal Crystal Jhumar",
    category: "jhumars",
    price: "INR 45,000",
    priceNum: 45000,
    description: "Majestic 24K gold-plated crystal chandelier with hand-cut Swarovski-style crystals.",
    fullDescription: "The Royal Crystal Jhumar is our crown jewel — a breathtaking chandelier featuring an ornate 24K gold-plated frame adorned with hundreds of hand-cut crystal pendants. Each crystal is meticulously selected for its refractive quality, creating a cascade of light that transforms any grand space. Suitable for ballrooms, bridal halls, and luxury reception areas. The warm amber glow emanating through its 18 E27 bulb sockets creates an atmosphere of timeless opulence.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=85",
    rating: 4.9,
    reviews: 24,
    specs: ["Material: Crystal & 24K Gold Plated Brass", "Diameter: 36 inches", "Height: 48 inches", "Bulbs: 18x E27", "Wattage: Max 720W", "Weight: 12 kg"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 2,
    name: "Venetian Gold Chandelier",
    category: "jhumars",
    price: "INR 62,000",
    priceNum: 62000,
    description: "Inspired by 17th-century Venetian craftsmanship with cascading amber glass droplets.",
    fullDescription: "Our Venetian Gold Chandelier draws inspiration from the legendary glass-blowing traditions of Murano, Italy. Each amber-tinted glass droplet is individually hand-blown and suspended from a hand-forged iron frame with an antique gold finish. The warm tones of the glass filter light into a honeyed glow, perfect for dining rooms and hotel lobbies seeking European grandeur. A true heirloom piece that grows more beautiful with time.",
    image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&q=85",
    rating: 4.8,
    reviews: 18,
    specs: ["Material: Blown Glass & Iron", "Diameter: 42 inches", "Height: 54 inches", "Bulbs: 24x E14", "Wattage: Max 480W", "Weight: 15 kg"],
    badge: "Premium",
    isNew: false
  },
  {
    id: 3,
    name: "Empire Brass Jhumar",
    category: "jhumars",
    price: "INR 38,500",
    priceNum: 38500,
    description: "Classic empire-style chandelier with polished brass arms and frosted glass shades.",
    fullDescription: "The Empire Brass Jhumar marries classical American Empire-period design with modern Pakistani craftsmanship. Its hand-polished solid brass arms sweep outward in graceful curves, each terminating in a frosted glass tulip shade that diffuses light beautifully. This timeless piece works equally well in traditional and contemporary interiors, from grand drawing rooms to boutique hotel suites. Comes with an adjustable chain for perfect ceiling height customization.",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=85",
    rating: 4.7,
    reviews: 31,
    specs: ["Material: Solid Brass & Frosted Glass", "Diameter: 30 inches", "Height: 36 inches", "Bulbs: 12x E27", "Wattage: Max 480W", "Weight: 8 kg"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 4,
    name: "Midnight Matte Jhumar",
    category: "jhumars",
    price: "INR 28,000",
    priceNum: 28000,
    description: "Sleek contemporary chandelier in matte black with geometric gold accents.",
    fullDescription: "For the modern luxury seeker, the Midnight Matte Jhumar presents a bold architectural statement. Its geometric frame finished in matte black creates a dramatic visual anchor, while the strategic gold accent rings add warmth and luxury. The integrated LED ring provides even, shadow-free illumination. This piece bridges the gap between industrial chic and contemporary opulence, making it perfect for modern apartments, restaurants, and creative spaces.",
    image: "https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=600&q=85",
    rating: 4.6,
    reviews: 15,
    specs: ["Material: Steel & Acrylic", "Diameter: 28 inches", "Height: 32 inches", "LED: Integrated 60W", "Color Temp: 3000K", "Weight: 5 kg"],
    badge: "New",
    isNew: true
  },
  {
    id: 5,
    name: "Golden Sconce Pair",
    category: "wall-lights",
    price: "INR 12,500",
    priceNum: 12500,
    description: "Elegant pair of wall-mounted sconces with brushed gold finish and white linen shades.",
    fullDescription: "Available as an exquisite matched pair, our Golden Sconce Wall Lights bring the warmth of boutique hotel living to your home. Each sconce features a brushed gold base with gracefully curved arm, topped with a drum-shaped ivory linen shade. The soft, warm light cast by these sconces creates an intimate glow perfect for bedrooms, hallways, and dining rooms. Includes all mounting hardware for easy installation. Price is for a pair.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=85",
    rating: 4.9,
    reviews: 42,
    specs: ["Pair of 2 Sconces", "Material: Brass & Linen", "Width: 8 inches each", "Projection: 14 inches", "Bulbs: 2x E27 (40W max)", "Shade: Ivory Linen"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 6,
    name: "Art Deco Wall Light",
    category: "wall-lights",
    price: "INR 8,800",
    priceNum: 8800,
    description: "Geometric Art Deco inspired wall light with black and gold finish, frosted glass panel.",
    fullDescription: "Channel the glamour of the Roaring Twenties with our Art Deco Wall Light. Inspired by the geometric patterns of 1920s Paris, this wall light features a sunburst-pattern frosted glass panel encased in a bold black and gold frame. The angular, symmetrical design creates beautiful shadow patterns on walls, especially striking in hallways and powder rooms. A single piece that commands attention and elevates any wall to gallery-worthy status.",
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&q=85",
    rating: 4.7,
    reviews: 19,
    specs: ["Material: Iron & Frosted Glass", "Width: 12 inches", "Height: 20 inches", "Projection: 8 inches", "Bulbs: 1x G9 (40W max)", "Finish: Black & Gold"],
    badge: "Premium",
    isNew: false
  },
  {
    id: 7,
    name: "Crystal Drop Wall Lamp",
    category: "wall-lights",
    price: "INR 15,000",
    priceNum: 15000,
    description: "Luxury wall lamp with cascading crystal drops and chrome finish arm.",
    fullDescription: "The Crystal Drop Wall Lamp is an architectural jewel for your walls. A polished chrome arm extends gracefully from the wall, terminating in a cluster of hand-strung crystal drops that shimmer with every movement of air. Ideal for master bedrooms, luxury en-suites, and boutique hotel rooms. The crystal arrangement can be customized in length for dramatic or subtle effects. Each piece is handcrafted and no two are exactly alike.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=85",
    rating: 4.8,
    reviews: 11,
    specs: ["Material: Crystal & Chrome", "Width: 10 inches", "Height: 24 inches", "Projection: 12 inches", "Bulbs: 1x E27 (60W max)", "Crystal: Clear K9"],
    badge: "New",
    isNew: true
  },
  {
    id: 8,
    name: "Arabesque Wall Hanging",
    category: "wall-hangings",
    price: "INR 18,500",
    priceNum: 18500,
    description: "Intricate hand-forged iron wall hanging with Arabesque patterns and gold leaf details.",
    fullDescription: "The Arabesque Wall Hanging is a masterpiece of Islamic geometric art translated into three dimensions. Our master artisans spend over 40 hours hand-forging and cutting each intricate lattice pattern from solid iron, which is then treated with multiple layers of black patina and highlighted with genuine gold leaf. The depth of the design creates stunning layered shadows that shift throughout the day with natural light. A conversation piece of museum quality.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=85",
    rating: 5.0,
    reviews: 8,
    specs: ["Material: Solid Iron & Gold Leaf", "Width: 48 inches", "Height: 36 inches", "Depth: 3 inches", "Weight: 6 kg", "Finish: Black Patina & Gold"],
    badge: "Custom",
    isNew: false
  },
  {
    id: 9,
    name: "Macramé Bohemian Hanging",
    category: "wall-hangings",
    price: "INR 6,500",
    priceNum: 6500,
    description: "Handwoven natural cotton macramé wall hanging with driftwood rod and gold beads.",
    fullDescription: "For spaces that blend luxury with natural warmth, our Macramé Bohemian Hanging brings an artisanal soul. Each piece is hand-knotted by skilled weavers using 100% natural cotton cord in ivory and natural tones, suspended from a smooth driftwood rod. Scattered throughout the knot work are hand-painted gold ceramic beads that catch light subtly. No two pieces are identical. Pairs beautifully with earthy tones, rattan furniture, and minimalist interiors.",
    image: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600&q=85",
    rating: 4.6,
    reviews: 27,
    specs: ["Material: Natural Cotton & Driftwood", "Width: 30 inches", "Length: 45 inches", "Color: Ivory & Natural", "Beads: Gold Ceramic", "Handmade: Yes"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 10,
    name: "Floral Metal Wall Art",
    category: "wall-hangings",
    price: "INR 22,000",
    priceNum: 22000,
    description: "3D sculptural metal wall art with blooming roses in rose gold powder coat.",
    fullDescription: "Our Floral Metal Wall Art transforms bare walls into living gardens. Crafted from precision laser-cut steel, each petal is individually hand-bent and shaped before being assembled into a three-dimensional floral sculpture. The piece is finished in a rose gold powder coat that harmonizes beautifully with both warm and cool color palettes. The three-dimensional depth means the artwork looks different from every angle and in every light condition.",
    image: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&q=85",
    rating: 4.9,
    reviews: 14,
    specs: ["Material: Laser-Cut Steel", "Width: 36 inches", "Height: 36 inches", "Depth: 5 inches", "Finish: Rose Gold Powder Coat", "Weight: 4 kg"],
    badge: "Premium",
    isNew: false
  },
  {
    id: 11,
    name: "Flush Mount Crystal Ceiling",
    category: "ceiling-lights",
    price: "INR 32,000",
    priceNum: 32000,
    description: "Glamorous flush-mount ceiling light with tiered crystal rings and LED.",
    fullDescription: "The Flush Mount Crystal Ceiling Light brings chandelier drama to rooms with lower ceilings. Three concentric rings of K9 crystal prisms are suspended from a circular base in brushed chrome, creating a full 360-degree sparkle effect. The integrated LED system (dimmable) provides energy-efficient warm white light while illuminating the crystals from within. Perfect for master bedrooms, dining rooms, and boutique retail spaces where ceiling height is limited.",
    image: "https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=600&q=85",
    rating: 4.8,
    reviews: 22,
    specs: ["Material: K9 Crystal & Chrome", "Diameter: 24 inches", "Height: 10 inches (flush)", "LED: 80W Integrated", "Color Temp: 3000K", "Dimmable: Yes"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 12,
    name: "Nordic Pendant Cluster",
    category: "ceiling-lights",
    price: "INR 24,500",
    priceNum: 24500,
    description: "Scandinavian-inspired cluster of 9 glass globe pendants in varying sizes.",
    fullDescription: "The Nordic Pendant Cluster celebrates the beauty of simplicity elevated to art. Nine hand-blown clear glass globes in three sizes hang at staggered heights from a single brass ceiling canopy, creating an organic, cloud-like installation. Each globe houses a single vintage Edison bulb, and when illuminated together, they create a constellation effect. Ideal for open-plan living areas, kitchen islands, and restaurant spaces that want warmth without heaviness.",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&q=85",
    rating: 4.7,
    reviews: 33,
    specs: ["9 Glass Globes", "Material: Blown Glass & Brass", "Spread: 40 inches", "Height: Adjustable 20-60 inches", "Bulbs: 9x E27 Edison", "Canopy: Brass"],
    badge: "New",
    isNew: true
  },
  {
    id: 13,
    name: "Moroccan Lantern Light",
    category: "ceiling-lights",
    price: "INR 16,000",
    priceNum: 16000,
    description: "Authentic Moroccan-style pierced brass lantern with colored glass inserts.",
    fullDescription: "Bring the magic of a Marrakech medina into your home with our Moroccan Lantern Light. Hand-hammered from solid brass by craftsmen using traditional techniques, each lantern features intricate geometric piercing through which colored glass inserts — deep ruby, sapphire, and emerald — cast jewel-toned patterns of light across walls and ceilings. Suspended on an ornate chain, this pendant creates an immersive atmosphere perfect for dining rooms, sitting areas, and eclectic interiors.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=85",
    rating: 4.9,
    reviews: 17,
    specs: ["Material: Solid Brass & Colored Glass", "Diameter: 16 inches", "Height: 28 inches", "Chain Length: 40 inches", "Bulbs: 1x E27 (60W max)", "Glass Colors: Ruby, Sapphire, Emerald"],
    badge: "Premium",
    isNew: false
  },
  {
    id: 14,
    name: "Opulent Marble Table Lamp",
    category: "table-lamps",
    price: "INR 18,000",
    priceNum: 18000,
    description: "White Carrara marble base table lamp with gold-rimmed ivory drum shade.",
    fullDescription: "The Opulent Marble Table Lamp is the ultimate expression of understated luxury. The base is carved from genuine white Carrara marble, with natural grey veining that makes each piece unique. A polished gold collar connects the marble to the lamp rod, crowned by an ivory drum shade with a gold trim ring. This lamp functions equally as functional lighting and sculptural art. Available in white, black, and grey marble variants upon custom order.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=85",
    rating: 5.0,
    reviews: 9,
    specs: ["Base: Carrara Marble", "Shade: Ivory Linen + Gold Trim", "Total Height: 28 inches", "Shade Diameter: 16 inches", "Bulbs: 1x E27 (60W max)", "Weight: 4 kg"],
    badge: "Premium",
    isNew: false
  },
  {
    id: 15,
    name: "Crystal Bedside Lamp",
    category: "table-lamps",
    price: "INR 9,500",
    priceNum: 9500,
    description: "Sparkling crystal body table lamp with blush pink fabric shade, sold as a pair.",
    fullDescription: "Perfect for symmetrical bedside styling, our Crystal Bedside Lamp set features faceted K9 crystal bodies that catch light from every angle, mounted on chrome bases. The blush pink fabric shades add a touch of romantic femininity that complements both contemporary and classic bedrooms. Sold as a set of two for perfectly matched nightstands. The touch-dimmer base allows for three levels of brightness, creating the perfect reading or ambient atmosphere.",
    image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&q=85",
    rating: 4.8,
    reviews: 38,
    specs: ["Set of 2 Lamps", "Base: K9 Crystal & Chrome", "Shade: Blush Pink Fabric", "Height: 22 inches", "Shade Width: 12 inches", "Touch Dimmer: 3 levels"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 16,
    name: "Industrial Edison Lamp",
    category: "table-lamps",
    price: "INR 7,200",
    priceNum: 7200,
    description: "Retro-industrial style table lamp with adjustable iron arm and exposed Edison bulb.",
    fullDescription: "The Industrial Edison Lamp celebrates raw beauty and mechanical elegance. An adjustable articulated iron arm clamps onto a weighted base finished in matte black, allowing the lamp head to be positioned precisely where light is needed. The exposed vintage Edison carbon-filament bulb (included) casts a warm amber glow that's both atmospheric and practical. Perfect for home offices, studio apartments, and workspace corners that need character and function.",
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&q=85",
    rating: 4.5,
    reviews: 45,
    specs: ["Material: Iron & Leather Cord", "Arm Reach: 24 inches adjustable", "Finish: Matte Black", "Bulb: Edison E27 40W (included)", "Base Weight: 1.5 kg", "Cord: 6 feet braided"],
    badge: "New",
    isNew: true
  },
  {
    id: 17,
    name: "Garden Lantern Post Light",
    category: "outdoor-lights",
    price: "INR 14,500",
    priceNum: 14500,
    description: "Weatherproof outdoor post lantern in antique bronze with seeded glass panels.",
    fullDescription: "Transform your garden pathways and entrance driveways with our Garden Lantern Post Light. The traditional lantern-style housing is crafted from die-cast aluminum with an antique bronze powder coat finish that is fully UV and weather resistant. Seeded glass panels diffuse light into gentle, texture-rich patterns. The IP65 rating ensures reliable performance through Pakistan's monsoon season. Available with or without post; post height can be customized.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=85",
    rating: 4.7,
    reviews: 20,
    specs: ["Material: Die-Cast Aluminum", "Finish: Antique Bronze", "Glass: Seeded Clear", "IP Rating: IP65 Weatherproof", "Bulbs: 1x E27 (60W max)", "Post: Optional (sold separately)"],
    badge: "Bestseller",
    isNew: false
  },
  {
    id: 18,
    name: "LED Garden Spotlight Set",
    category: "outdoor-lights",
    price: "INR 11,000",
    priceNum: 11000,
    description: "Set of 6 adjustable outdoor LED spotlights with ground stakes for landscaping.",
    fullDescription: "Professionally illuminate your garden, trees, and architectural features with our LED Garden Spotlight Set. Six high-powered LED spotlights (20W each) come complete with ground stakes for easy installation in soil or grass. Each spotlight has a 180-degree adjustable head for precise aiming. The warm white 3000K light temperature enhances the natural colors of plants and stone. All-weather construction with IP67 rating ensures year-round performance in any conditions.",
    image: "https://images.unsplash.com/photo-1565182999561-18d7dc61c393?w=600&q=85",
    rating: 4.6,
    reviews: 13,
    specs: ["Set of 6 Spotlights", "Power: 20W each LED", "Color Temp: 3000K Warm White", "IP Rating: IP67", "Beam Angle: 24 degrees", "Cable: 3m each"],
    badge: "New",
    isNew: true
  },
  {
    id: 19,
    name: "Mughal Arch Jhumar",
    category: "jhumars",
    price: "INR 75,000",
    priceNum: 75000,
    description: "Grand custom jhumar featuring Mughal arch motifs, emerald glass drops and 22K gold plating.",
    fullDescription: "The Mughal Arch Jhumar is our most prestigious creation — a bespoke masterpiece that takes 60+ hours to craft. Inspired by the arched niches of Lahore's Wazir Khan Mosque, this chandelier features interlocking Mughal arch frames in 22K gold-plated brass. From each arch hang deep emerald-green glass drops alongside clear crystal cascades, creating a symphony of color and light. This piece is typically made to order and becomes the statement centerpiece of the grandest halls and marquees.",
    image: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=600&q=85",
    rating: 5.0,
    reviews: 5,
    specs: ["Material: 22K Gold Plated Brass, Emerald Glass, Crystal", "Diameter: 48 inches", "Height: 60 inches", "Bulbs: 30x E14 Candelabra", "Wattage: Max 600W", "Lead Time: 3-4 weeks"],
    badge: "Custom",
    isNew: false
  },
  {
    id: 20,
    name: "Bamboo Pendant Light",
    category: "ceiling-lights",
    price: "INR 8,500",
    priceNum: 8500,
    description: "Eco-luxury handwoven bamboo pendant shade with natural rope suspension.",
    fullDescription: "For spaces that celebrate natural luxury, our Bamboo Pendant Light is a sustainable statement piece. Each shade is hand-woven by artisans in the traditional cane-weaving districts of Sindh using naturally sourced bamboo strips. The weave pattern allows light to filter through in a honeyed, dappled pattern that warms any space. Suspended on twisted natural jute rope from a brass canopy, this pendant works beautifully in restaurants, eco-resorts, bohemian homes, and coastal retreats.",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=85",
    rating: 4.5,
    reviews: 29,
    specs: ["Material: Natural Bamboo & Jute", "Diameter: 18 inches", "Height: 20 inches", "Suspension: 5 feet jute rope", "Bulbs: 1x E27 (60W max)", "Canopy: Brushed Brass"],
    badge: "New",
    isNew: true
  }
];
